### ISSUE TITLE
Posts not rendered in template (on production)

### ISSUE THREAD

**Issue by LaundroMat** [bunchesofdonald/django-hermes#11]
I have a very strange issue that might very well be related to fatigue, but for the life of me I cannot figure out what could be wrong.

I have installed hermes from github via -e git+https://github.com/LaundroMat/django-hermes.git#egg=django-hermes (it's a clone of hermes v1.4.2)

On my development machine (a virtualenv), everything works fine. I have added some posts, created a directory hermes with post_list.html and post_detail.html under my core apps templates directory.

Django finds everything nicely and the post_list.html template

    {% extends "base.html" %}
    {% load staticfiles %}
    {% block content %}    
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-xs-12">
                <h2>Latest blog articles</h2>
                    <ul>
                        {% for p in posts %}
                        <li>
                            <p><a href="{{ p.get_absolute_url }}">{{ p.subject }}</a></p>
                            <p class="small">
                            a {{ p.reading_time|floatformat:"1" }} minute read
                            </p>
                        </li>
                        {% endfor %}
                    </ul>
            </div>
        </div>
    </div>
    {% endblock %}

renders an overview of the posts:

![capture](https://cloud.githubusercontent.com/assets/42320/9407880/9c68006e-480d-11e5-93be-74716e12bbe9.PNG)

But when I try this on staging (or production), while there *are* posts in the database (checked and double-checked in the admin as well as via the shell):

![capture](https://cloud.githubusercontent.com/assets/42320/9407735/709861b4-480c-11e5-87b4-ba2e1e746ef5.PNG)

they simply won't show up:

![capture](https://cloud.githubusercontent.com/assets/42320/9407746/8570b550-480c-11e5-83df-6698f693b80e.PNG)

The code (and templates) are exactly the same as on my development environment...

I'm sure I'm missing something extremely obvious, but I can't figure out what it could be.

**Comment by LaundroMat** [comment]
Waw, I'm an idiot. You can delete this issue (if that's possible). 

I imported the posts from my dev environment but forgot that I hadn't set `published` to True yet.

**Comment by bunchesofdonald** [comment]
No worries, I'm glad you got the issue figured out. I don't think I can delete it, so I'll just close it out.
