### ISSUE TITLE
Custom User model

### ISSUE THREAD

**Issue by fproldan** [bunchesofdonald/django-hermes#9]
ERRORS:
hermes.Post.author: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
	HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.

**Comment by bunchesofdonald** [comment]
Yep, that's absolutely an issue. I'll get a fix out later today.

**Comment by fproldan** [comment]
Thanks! Btw, very useful app.

**Comment by bunchesofdonald** [comment]
Fixed in https://github.com/bunchesofdonald/django-hermes/commit/16c326204dddd297e6ab80246844ff2bba039427

**Comment by bunchesofdonald** [comment]
I've released version 1.4.2, this issue should be fixed. Feel free to re-open this if you run into issues again. Again thank you so much for reporting this and the kind words!
